apiVersion: v1
kind: Pod
metadata:
  name: kube-attach
  namespace: default
spec:
  containers:
    - args:
        - -c
        - n=0; while [ $n -lt 10 ]; do echo hello-3-5; sleep 1; n=$((n+1)); done ; sleep
          20000
      command:
        - /bin/sh
      image: 10.24.6.41:80/ubuntu
      imagePullPolicy: Always
      name: kube-attach
      resources: {}
      securityContext:
        privileged: false
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-889nl
          readOnly: true
  dnsPolicy: ClusterFirst
  serviceAccount: default
  serviceAccountName: default
  volumes:
    - name: default-token-889nl
      secret:
        defaultMode: 420
        secretName: default-token-889nl
